#include "shaders/image.h"

const char *image_vs =
  "#version 330\n"
  "#define M_PI 3.1415926535897932384626433832795\n"
  "layout(location=0) in vec2 iPos;"
  "layout(location=1) in vec2 iTexCoord;"
  "out vec2 vTexCoord;"
  "uniform highp vec2 uResolution,uBaseResolution,uPosition;"
  "uniform highp float uRotation,uScale;"
  "uniform highp vec2 uPivot,uSize;"
  "vec2 v(vec2 u,float v)"
  "{"
    "float i=cos(v);"
    "v=sin(v);"
    "return vec2(u.x*i-u.y*v,u.y*i+u.x*v);"
  "}"
  "void main()"
  "{"
    "vTexCoord=iTexCoord;"
    "vec2 u=iPos;"
    "float i=uBaseResolution.x/uBaseResolution.y;"
    "vec2 n=vec2(uSize.x/uBaseResolution.x*i,uSize.y/uBaseResolution.y)*uScale;"
    "u=v((u-uPivot)*n,uRotation)+uPivot*n+vec2(uPosition.x/uBaseResolution.x*i,uPosition.y/uBaseResolution.y);"
    "u.y=-u.y;"
    "u=u*2-vec2(i,-1);"
    "u.x/=i;"
    "u=u*(uBaseResolution/uResolution)*(uResolution.y/uBaseResolution.y);"
    "gl_Position=vec4(u,0,1);"
  "}";

const char *image_fs =
  "#version 330\n"
  "in vec2 vTexCoord;"
  "out vec4 vColor;"
  "uniform sampler2D uTexture0;"
  "uniform highp vec4 uColor;"
  "void main()"
  "{"
    "vec4 v=texture(uTexture0,vTexCoord);"
    "if(v.w<.5)"
      "discard;"
    "vColor=v*uColor;"
  "}";