#include "textsh.h"

const char* textsh_vs = ""
  "#version 330 core\n"
  "\n"
  "precision lowp int;\n"
  "precision lowp float;\n"
  "\n"
  "layout(location = 0) in vec2 iPos;\n"
  "\n"
  "out vec2 vTexCoord;\n"
  "\n"
  "uniform vec2 uResolution;\n"
  "uniform vec2 uBaseResolution;\n"
  "\n"
  "uniform vec2 uLocation;\n"
  "uniform vec2 uSize;\n"
  "uniform uvec2 uLayout;\n"
  "uniform uint uIndex;\n"
  "\n"
  "void main() {\n"
  "  // Tex coords\n"
  "  uint cols = uLayout.x;\n"
  "  uint rows = uLayout.y;\n"
  "\n"
  "  float w = 1.0 / float(cols);\n"
  "  float h = 1.0 / float(rows);\n"
  "\n"
  "  float col = float(uIndex % cols);\n"
  "  float row = float(uIndex / cols);\n"
  "\n"
  "  vTexCoord = vec2(\n"
  "    (col + iPos.x) * w,\n"
  "    (row + iPos.y) * h\n"
  "  );\n"
  "\n"
  "  // Position btw\n"
  "  vec2 pos = iPos;\n"
  "\n"
  "  float aspect = uBaseResolution.x / uBaseResolution.y;\n"
  "  vec2 size = vec2(\n"
  "    uSize.x / uBaseResolution.x * aspect,\n"
  "    uSize.y / uBaseResolution.y * 1\n"
  "  );\n"
  "\n"
  "  pos *= size;\n"
  "  pos += vec2(\n"
  "    uLocation.x / uBaseResolution.x * aspect,\n"
  "    uLocation.y / uBaseResolution.y\n"
  "  );\n"
  "\n"
  "  pos.y = -pos.y;\n"
  "\n"
  "  pos *= 2;\n"
  "  pos -= vec2(1.0 * aspect, -1.0);\n"
  "\n"
  "  pos.x /= aspect;\n"
  "\n"
  "  pos *= uBaseResolution / uResolution;\n"
  "  pos *= uResolution.y / uBaseResolution.y;\n"
  "\n"
  "  gl_Position = vec4(pos, 0.0, 1.0);\n"
  "}";

const char* textsh_fs = ""
  "#version 330 core\n"
  "\n"
  "precision lowp float;\n"
  "precision lowp int;\n"
  "\n"
  "in vec2 vTexCoord;\n"
  "\n"
  "out vec4 oColor;\n"
  "\n"
  "uniform sampler2D uTexture0;\n"
  "uniform vec4 uColor;\n"
  "\n"
  "void main() {\n"
  "  oColor = texture(uTexture0, vTexCoord) * uColor;\n"
  "}";
